### ISSUE TITLE
64Bit Support?

### ISSUE THREAD

**Issue by Marco-Total** [xkonni/raspberry-remote#38] opened 2021-01-19 07:49 UTC
Hi,

when I try to run under raspberry pi os 64Bit I get an error message. How can I get this nice tool to work on a 64bit OS?

```
root@mapi24:/home/pi/raspberry-remote# make
g++ -Wall -lwiringPi   -c -o RCSwitch.o RCSwitch.cpp
RCSwitch.cpp:31:42: warning: converting to non-pointer type ‘long unsigned int’ from NULL [-Wconversion-null]
 unsigned long RCSwitch::nReceivedValue = NULL;
                                          ^~~~
RCSwitch.cpp: In constructor ‘RCSwitch::RCSwitch()’:
RCSwitch.cpp:41:30: warning: converting to non-pointer type ‘long unsigned int’ from NULL [-Wconversion-null]
   RCSwitch::nReceivedValue = NULL;
                              ^~~~
RCSwitch.cpp: In member function ‘void RCSwitch::enableReceive()’:
RCSwitch.cpp:575:32: warning: converting to non-pointer type ‘long unsigned int’ from NULL [-Wconversion-null]
     RCSwitch::nReceivedValue = NULL;
                                ^~~~
RCSwitch.cpp:576:36: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
     RCSwitch::nReceivedBitlength = NULL;
                                    ^~~~
RCSwitch.cpp: In member function ‘bool RCSwitch::available()’:
RCSwitch.cpp:588:38: warning: NULL used in arithmetic [-Wpointer-arith]
   return RCSwitch::nReceivedValue != NULL;
                                      ^~~~
RCSwitch.cpp: In member function ‘void RCSwitch::resetAvailable()’:
RCSwitch.cpp:592:30: warning: converting to non-pointer type ‘long unsigned int’ from NULL [-Wconversion-null]
   RCSwitch::nReceivedValue = NULL;
                              ^~~~
g++ -Wall -lwiringPi   -c -o daemon.o daemon.cpp
daemon.cpp: In function ‘int main(int, char**)’:
daemon.cpp:277:22: warning: ‘sprintf’ writing a terminating nul past the end of the destination [-Wformat-overflow=]
         sprintf(msg, "nState[%d] = %d", nAddr, nState[nAddr]);
                      ^~~~~~~~~~~~~~~~~
daemon.cpp:277:16: note: ‘sprintf’ output between 14 and 34 bytes into a destination of size 13
         sprintf(msg, "nState[%d] = %d", nAddr, nState[nAddr]);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
daemon.cpp:173:22: warning: ‘sprintf’ writing a terminating nul past the end of the destination [-Wformat-overflow=]
         sprintf(msg, "nState[%d] = %d", nAddr, nState[nAddr]);
                      ^~~~~~~~~~~~~~~~~
daemon.cpp:173:16: note: ‘sprintf’ output between 14 and 34 bytes into a destination of size 13
         sprintf(msg, "nState[%d] = %d", nAddr, nState[nAddr]);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
g++ -Wall -pthread RCSwitch.o daemon.o -o daemon -Wall -lwiringPi
/usr/bin/ld: inkompatibles /usr/lib/gcc/aarch64-linux-gnu/8/../../../../lib/libwiringPi.so wird bei der Suche nach -lwiringPi übersprungen
/usr/bin/ld: inkompatibles /usr/lib/../lib/libwiringPi.so wird bei der Suche nach -lwiringPi übersprungen
/usr/bin/ld: inkompatibles /usr/lib/gcc/aarch64-linux-gnu/8/../../../libwiringPi.so wird bei der Suche nach -lwiringPi übersprungen
/usr/bin/ld: inkompatibles //usr/lib/libwiringPi.so wird bei der Suche nach -lwiringPi übersprungen
/usr/bin/ld: -lwiringPi kann nicht gefunden werden
collect2: error: ld returned 1 exit status
make: *** [Makefile:11: daemon] Fehler 1
```

**Comment by xkonni** [comment] 2021-01-21 08:41
duplicate of #37

**Closed as completed by xkonni** 2021-01-21 08:41 UTC
